#!/usr/bin/env bash
# shellcheck disable=SC2034
# exported happen via `export_fun`, but shellcheck can't see that
BASH_ENV=~/.bash_env
EDITOR=vim
GREP_OPTIONS="--colour=auto"
LESS=FSRX
LESSHISTFILE=-
PAGER=less
RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

# Contains a list of environment variables that TMUX should update when a new
# client connects to a session
TMUX_REFRESH_VARS="TMUX_REFRESH_VARS"

# Ensure we always use the most recent SSH_AUTH_SOCK/DISPLAY variables within
# tmux.
if [[ -n "$SSH_AUTH_SOCK" ]]; then
    TMUX_REFRESH_VARS="SSH_AUTH_SOCK $TMUX_REFRESH_VARS"
fi
if [[ -n "$DISPLAY" ]]; then
    TMUX_REFRESH_VARS="DISPLAY $TMUX_REFRESH_VARS"
fi

export_fun () {
    for var in "$@"; do
        export -- "${var?}"
        TMUX_REFRESH_VARS="$var $TMUX_REFRESH_VARS"
    done
}

# Store the "original" PATH and MANPATH in BASEPATH and BASEMANPATH
# respectively, so that re-evaluating .bash_env does not infinitely expand the
# variables.
BASEPATH="${BASEPATH:-$PATH}"
export_fun BASEPATH
PATH="$BASEPATH"
BASEMANPATH="${BASEMANPATH:-$MANPATH}"
export_fun BASEMANPATH
MANPATH="$BASEMANPATH"

# Stop globs with no matches to expand to themselves in bash.
# Conditional, because this errors on macOS when zsh is the default
if [[ -n "$BASH_VERSION" ]]; then
    shopt -s nullglob
fi

os_name="$(uname)"
if [[ "$os_name" = "Darwin" ]]; then
    LANG=en_US.UTF-8
    LC_ALL=en_US.UTF-8

    if [[ -d "/opt/local/" ]]; then
        MANPATH="/opt/local/share/man:$MANPATH"
        PATH="/opt/local/bin:/opt/local/sbin:$PATH"
    fi

    if [[ -d "/Library/Application Support/Tarsnap/" ]]; then
        MANPATH="/Library/Application Support/Tarsnap/share/man:$MANPATH"
        PATH="/Library/Application Support/Tarsnap/bin:$PATH"
    fi

    if [[ -d "/Applications/Racket v6.1.1/bin/" ]]; then
        PATH="/Applications/Racket v6.1.1/bin/:$PATH"
    fi

    if [[ -d "/opt/homebrew/bin/" ]]; then
        MANPATH="/opt/homebrew/share/man:$MANPATH"
        PATH="/opt/homebrew/bin/:$PATH"
    fi

    export_fun LANG LC_ALL MANPATH DYLD_LIBRARY_PATH
fi

ghcdefault=902
ghcdirs=(~/ghc/[0-9][0-9][0-9]/)
for dir in "${ghcdirs[@]}"; do
    ghcdir="$(basename "$dir")"
    if [[ "$ghcdir" != "$ghcdefault" ]]; then
        PATH="${dir}bin:$PATH"
    fi
done

if [[ -d "$HOME/ghc/$ghcdefault/bin" ]]; then
    PATH="$HOME/ghc/$ghcdefault/bin:$PATH"
fi

if [[ -d "$HOME/.cabal/" ]]; then
    PATH="$HOME/.cabal/bin/:$PATH"
fi

# Read and set any machine local overrides
# Stop shellcheck from checking file, it may not exist
# shellcheck disable=SC1090
[[ -f ~/.bash_env_local ]] && . ~/.bash_env_local

PATH="$HOME/.bin:$PATH"

export_fun BASH_ENV EDITOR GREP_OPTIONS LESS LESSHISTFILE PAGER PATH
export_fun RIPGREP_CONFIG_PATH
export TMUX_REFRESH_VARS

# When sourced within tmux, immediately update the values in the global
# environment
if [[ -n "$TMUX" ]]; then
    tmux set update-environment "$TMUX_REFRESH_VARS"
    for var in ${TMUX_REFRESH_VARS//:/$IFS}; do
        tmux set-environment "$var" "${!var}"
    done
fi
