FILE="vimplugins/install.sh"
bundle_dir="$HOME/.vim/bundle"

install_repo "$bundle_dir" "git+https://github.com/trefis/coquille.git"
install_repo "$bundle_dir" "git+https://github.com/kien/ctrlp.vim.git"
install_repo "$bundle_dir" "ssh://hg@bitbucket.org/sjl/gundo.vim"
install_repo "$bundle_dir" "git+https://github.com/merijn/haskellFoldIndent.git"
install_repo "$bundle_dir" "git+https://github.com/kien/rainbow_parentheses.vim.git"
install_repo "$bundle_dir" "git+https://github.com/scrooloose/syntastic.git"
install_repo "$bundle_dir" "git+https://github.com/majutsushi/tagbar.git"
install_repo "$bundle_dir" "git+https://github.com/bitc/vim-hdevtools.git"
install_repo "$bundle_dir" "git+https://github.com/Twinside/vim-hoogle.git"
install_repo "$bundle_dir" "git+https://github.com/tpope/vim-pathogen.git"
install_repo "$bundle_dir" "git+https://github.com/tpope/vim-surround.git"
install_repo "$bundle_dir" "git+https://github.com/def-lkb/vimbufsync.git"
