FILE="vimplugins/install.sh"
bundle_dir="$HOME/.vim/bundle"

install_repo "$bundle_dir" "git+https://github.com/trefis/coquille.git"
install_repo "$bundle_dir" "git+https://github.com/ctrlpvim/ctrlp.vim.git"
install_repo "$bundle_dir" "https://bitbucket.org/sjl/gundo.vim"
install_repo "$bundle_dir" "git+https://github.com/merijn/haskellFoldIndent.git"
install_repo "$bundle_dir" "git+https://github.com/kien/rainbow_parentheses.vim.git"
install_repo "$bundle_dir" "git+https://github.com/majutsushi/tagbar.git"
install_repo "$bundle_dir" "git+https://github.com/Twinside/vim-hoogle.git"
install_repo "$bundle_dir" "git+https://github.com/tpope/vim-pathogen.git"
install_repo "$bundle_dir" "git+https://github.com/tpope/vim-surround.git"
install_repo "$bundle_dir" "git+https://github.com/def-lkb/vimbufsync.git"
install_repo "$bundle_dir" "git+https://github.com/eagletmt/ghcmod-vim.git"
install_repo "$bundle_dir" "git+https://github.com/Shougo/vimproc.vim.git"
install_repo "$bundle_dir" "git+https://github.com/godlygeek/tabular.git"
install_repo "$bundle_dir" "git+https://github.com/eagletmt/neco-ghc.git"
install_repo "$bundle_dir" "git+https://github.com/ervandew/supertab.git"
install_repo "$bundle_dir" "git+https://github.com/neovimhaskell/haskell-vim.git"
install_repo "$bundle_dir" "git+https://github.com/JKirchartz/writegooder.vim.git"
install_repo "$bundle_dir" "git+https://github.com/neomake/neomake.git"
install_repo "$bundle_dir" "git+https://github.com/lervag/vimtex.git"
install_repo "$bundle_dir" "git+https://github.com/ludovicchabant/vim-gutentags.git"
