FILE="vimplugins/install.sh"
bundle_dir="$HOME/.vim/bundle"

install_repo "$bundle_dir" "git+ssh://git@github.com:trefis/coquille.git"
install_repo "$bundle_dir" "git+ssh://git@github.com/kien/ctrlp.vim.git"
install_repo "$bundle_dir" "https://bitbucket.org/sjl/gundo.vim"
install_repo "$bundle_dir" "git+ssh://git@github.com:merijn/haskellFoldIndent.git"
install_repo "$bundle_dir" "git+ssh://git@github.com/kien/rainbow_parentheses.vim.git"
install_repo "$bundle_dir" "git+ssh://git@github.com/scrooloose/syntastic.git"
install_repo "$bundle_dir" "git+ssh://git@github.com/majutsushi/tagbar.git"
install_repo "$bundle_dir" "git+ssh://git@github.com/bitc/vim-hdevtools.git"
install_repo "$bundle_dir" "git+ssh://git@github.com/tpope/vim-pathogen.git"
install_repo "$bundle_dir" "git+ssh://git@github.com/tpope/vim-surround.git"
install_repo "$bundle_dir" "git+ssh://git@github.com:def-lkb/vimbufsync.git"
