#!/usr/bin/env bash

set -e

install_file () {
    # If the destination exists
    if [ -f "$1" -a -f "$2" ] || [ -d "$1" -a -d "$2" ] || [ -L "$2" ]; then
        # And is not a link to the right source
        if [ "$1" != "$(readlink "$2")" ]; then
            while true; do
                printf "Wrong source file found for:\n$2\n"
                printf "(D)iff changes/(O)verwrite file/(K)eep file? [Dok?] "
                read COMMAND

                if [ -z "$COMMAND" ]; then
                    COMMAND=d
                fi

                case "$COMMAND" in
                    [dD])
                        diff -u "$2" "$1" | less
                        ;;
                    [oO])
                        if rm "$2"; then
                            ln -s "$1" "$2"
                        else
                            printf "Failed to delete $2" 1>&2
                        fi
                        break
                        ;;
                    [kK])
                        break
                        ;;
                    ?)
                        echo yay!
                        ;;
                esac
            done
        fi
    else
        # The destination doesn't exists, so symlink it.
        ln -s "$1" "$2"
    fi
}

for link in dotfiles/*; do
    install_file "$(pwd)/$link" "$HOME/.${link##*/}"
done

for install_script in install/*/install.sh; do
    src="$(pwd)/${install_script%install.sh}"
    . "$install_script"
done
