#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

if [ "$(uname)" = "Darwin" ]; then
  . setup/osx
fi

set +o pipefail
if ! ssh -T git@github.com 2>&1 | grep -q merijn; then
    printf "Can't authenticate with github!\n"
    exit 1
fi
set -o pipefail

if ! type hg >/dev/null 2>&1; then
    printf "Mercurial not installed!\n"
    exit 1
fi

if [ ! -e ~/.hgrc ]; then
    cp dotfiles/hgrc ~/.hgrc
fi

if ! hg config extensions.hggit >/dev/null 2>&1; then
    printf "hg-git not installed!\n"
    exit 1
fi

exec ./check-config
