#!/usr/bin/env bash

logdate=$(date +%Y%m%d%H%M)
interrupted=0

trap - SIGQUIT
trap 'interrupted=1; printf "Terminating due to SIGTERM\n" >&2' SIGTERM
trap 'mv ${logdate}.Tarsnap.Error errors/ 2>/dev/null' EXIT

if [ $(($# % 2)) -ne 0 ]; then
    printf "Odd number of arguments! %s\n%s\n" \
           "Arguments to $0 must be pairs of name and directory. Received:" \
           "$@" 1>&2
    printf "Backup failed to run!" >${logdate}.Tarsnap.Error
    exit 1
fi

while [ $# -gt 0 ]; do
    bin/tarsnap -c -f "$1-$logdate" $2 &
    wait
    status=$?

    if [ $status -ne 0 ] && [ $interrupted -ne 0 ]; then
        kill -s SIGQUIT 0
        wait \
            && printf "Interrupted: $1\n" >>${logdate}.Tarsnap.Error \
            && shift 2


        while [ $# -gt 0 ]; do
            printf "Skipped: $1\n" >>${logdate}.Tarsnap.Error
            shift 2
        done

        break
    elif [ $status -ne 0 ]; then
        printf "Failed: $1\n" >>${logdate}.Tarsnap.Error
    fi

    shift 2
done
