#!/usr/bin/env bash
echo "Setting default configurations."

# Show bottom status bar with available space in finder
defaults write com.apple.finder ShowStatusBar -bool true

# Show full posix path in Finder title bars
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Disable the warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

# Don't create .DS_Store on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true

# Disable smart quotes as it’s annoying for messages that contain code
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticQuoteSubstitutionEnabled" -bool false


arch_name="$(uname -p)"
if [[ "$arch_name" = "arm" ]]; then
    if ! pgrep oahd >/dev/null 2>&1; then
        printf "Detected ARM and no Rosetta. Installing Rosetta 2.\n"
        sudo softwareupdate --install-rosetta
    fi
fi

hash brew 2>/dev/null || { echo >&2 "Homebrew not found. Aborting."; exit 1; }

echo "Installing Homebrew tools."
homebrew_formulae=(
    "bash"
    "bash-completion@2"
    "colordiff"
    "ctags"
    "neovim"
    "reattach-to-user-namespace"
    "ripgrep"
    "tmux"
    "wdiff"
)

brew install "${homebrew_formulae[@]}"

homebrew_casks=(
    "growlnotify"
    "karabiner-elements"
)

brew install --cask "${homebrew_casks[@]}"

homebrew_formulae_personal=(
    "irssi"
    "nethack"
    "sox"
    "urweb"
)

homebrew_casks_personal=(
    "mactex-no-gui"
)

while true; do
    # Prompt user for action
    read -rep "Personal machine? (Y/n) " \
        RESPONSE

    if [[ -z "$RESPONSE" ]]; then
        RESPONSE=Y
    fi

    case "$RESPONSE" in
        [yY])
            # Install personal casks/formulae
            brew install "${homebrew_formulae_personal[@]}"
            brew install --cask "${homebrew_casks_personal[@]}"
            break
            ;;
        [nN])
            # Skip personal casks/formulae
            break
            ;;
        *)
            ;;
    esac
done
